apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - name: app1
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Current date and time: $(date)" >> /output/success.txt; sleep 5; done']
    volumeMounts:
    - name: vol
      mountPath: /output
  - name: app2
    image: wbitt/network-multitool
    command: ['sh', '-c', 'tail -f /input/success.txt']
    volumeMounts:
    - name: vol
      mountPath: /input
  volumes:
    - name: vol
      hostPath:
        path: /var/netology
