apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod
  namespace: default
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
      ports:
        - containerPort: 38080
