---
all:
  hosts:
    sonar-01:
      ansible_host: 51.250.22.150
    nexus-01:
      ansible_host: 130.193.43.94
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: user