apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
spec:
  ports:
  - name: nginx
    port: 9001
    protocol: TCP
    targetPort: 80
  - name: multitool
    port: 9002
    protocol: TCP
    targetPort: 18080
  selector:
    app: nginx-deployment
