apiVersion: v1
kind: Service
metadata:
  name: deployment-svc-ext
spec:
  type: NodePort
  selector:
    app: nginx-deployment
  ports:
  - name: nginx
    port: 80
    nodePort: 30001
    protocol: TCP
    targetPort: 80
  
  
