apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: netology-web
  namespace: default
spec:
  containers:
    - name: echoserver-container
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      ports:
        - containerPort: 8080
